// Curated from the partner reference on 2026-09-05. No Google Sites code or investor records.
export const reference = {
  photos: {
    home: [
      "/images/home-01.png",
      "/images/home-02.png",
      "/images/home-03.png",
      "/images/home-04.png",
      "/images/home-05.png",
      "/images/home-06.png",
      "/images/home-07.png",
      "/images/home-08.png",
    ],
    "property-detail": ["/images/property-detail-01.png"],
  },
  processOverview: "/images/business-process.png",
  processSteps: [
    {
      id: "1",
      name: "Acquisition",
      title:
        "Step 1. Acquisition of Undervalued Affordable Single Family Homes",
      paragraphs: [
        "Obelisk specializes in acquiring undervalued affordable single-family homes in select U.S. markets where replacement costs significantly exceed acquisition costs and long-term rental demand remains durable. Our acquisition strategy is designed to create value at the point of purchase rather than relying on market appreciation alone.",
        "1.1 Market Selection. We focus on secondary and tertiary markets characterized by strong affordability advantages relative to national housing costs; stable working-class populations and durable rental demand; favorable landlord regulations; limited new housing supply; reliable housing subsidy programs, including Housing Choice Voucher (Section 8) participation. Our current operations are concentrated in the Birmingham, Alabama metropolitan area, where housing remains significantly below replacement cost while rental demand continues to be supported by population stability and a shortage of quality affordable housing. The Housing Authority of the Birmingham District administers one of the region's largest voucher programs, creating a substantial tenant pool for qualified rental housing.",
        "1.2 Property Sourcing. Obelisk sources opportunities through a combination of direct-to-seller outreach; local wholesaler relationships; off-market transactions; distressed asset purchases; estate sales and absentee-owner dispositions; MLS opportunities overlooked by institutional buyers. We prioritize situations where operational inefficiencies, deferred maintenance, ownership fatigue, or capital constraints create pricing dislocations.",
        "1.3 Acquisition Criteria. Each property is evaluated using a disciplined underwriting framework that considers purchase price relative to replacement cost; renovation scope and capital requirements; expected stabilized rent; Section 8 payment standards and subsidy support; neighborhood-level occupancy trends; projected operating expenses; long-term cash flow durability. Properties must demonstrate a clear path to generating attractive risk-adjusted returns after renovation and stabilization.",
        "1.4 Density and Portfolio Construction. Unlike many institutional buyers pursuing scattered acquisitions across multiple states, Obelisk intentionally builds geographic density within specific neighborhoods and submarkets. This approach creates operational efficiencies, improves contractor utilization, reduces maintenance costs, and strengthens local market intelligence.",
      ],
      image: "/images/process-acquisition.png",
    },
    {
      id: "2",
      name: "Renovation",
      title: "Step 2. Renovation: Compliance-Led, Value-Engineered",
      paragraphs: [
        "Obelisk takes a fundamentally different approach to renovating affordable rental housing. Our objective is not to maximize renovation spend or create luxury homes. It is to deliver safe, durable, attractive housing that performs above Section 8 requirements—without over-improving the asset. We begin with the applicable Housing Choice Voucher inspection and habitability requirements and use them as the baseline for every renovation. From there, we selectively invest in improvements that meaningfully increase durability, tenantability, rentability, and long-term operating performance.",
        "This creates a disciplined renovation philosophy: Meet the standard. Exceed it where it matters. Avoid spending where it doesn't.",
        "Our renovation scope typically prioritizes:",
        "Health & safety: electrical, plumbing, HVAC, roofing, structural and other critical systems",
        "Habitability: functional kitchens, bathrooms, flooring, doors, windows, lighting, and essential appliances",
        "Durability: materials and finishes selected to withstand the higher turnover and maintenance demands of affordable rental housing",
        "Tenant appeal: clean, modern, neutral finishes that improve leasing without introducing unnecessary luxury specifications",
        "Inspection readiness: completing work to a standard that minimizes failed inspections, delays, and avoidable vacancy",
        "We deliberately avoid renovations that have little relationship to rental income or operating performance. Premium finishes, unnecessary cosmetic upgrades, and luxury amenities may increase the property's cost without producing a corresponding increase in rent, occupancy, or long-term value. The result is a “slightly-above-standard” renovation model: every home is brought to a consistent institutional operating standard, but capital is deployed only where it creates measurable value.",
        "This philosophy is particularly important in Section 8-oriented housing. Because rental income is constrained by local payment standards and the economics of affordable housing, every renovation dollar must earn its place in the capital budget. Obelisk therefore treats renovation not as a construction project, but as an investment allocation decision—balancing upfront capital expenditure against rent, occupancy, maintenance, useful life, and ultimately property-level cash flow. We don't renovate to impress. We renovate to perform.",
      ],
      image: "/images/process-renovation.png",
    },
    {
      id: "3",
      name: "Leasing",
      title: "Step 3. Leasing: Disciplined Screening, Expert Execution",
      paragraphs: [
        "Leasing affordable housing requires more than filling vacancies. Obelisk combines rigorous tenant screening with deep proficiency in government housing programs to convert renovated properties into stable, cash-flowing assets. ",
        "We apply disciplined screening criteria to evaluate each applicant's income, rental history, credit profile, household composition, and ability to meet lease obligations. Section 8 participation does not eliminate the need for tenant selection—it makes disciplined screening even more important. Our objective is to identify residents who are likely to maintain the property, comply with the lease, and contribute to long-term occupancy stability.",
        "At the same time, Section 8 leasing involves a complex administrative process involving the Public Housing Authority (PHA), Housing Assistance Payments (HAP), inspections, rent reasonableness determinations, tenant certifications, documentation, and ongoing compliance. Obelisk has developed operating expertise around these procedures to reduce administrative friction and accelerate the path from vacancy to stabilized rental income.",
        "Our leasing process focuses on three outcomes:",
        "1) Qualified Tenants. We maintain rigorous screening standards and do not equate voucher eligibility with automatic tenant approval.",
        "2) Government Process Proficiency. We understand the documentation, inspection, approval, and payment procedures required to successfully place and retain Section 8 tenants.",
        "3) Speed to Stabilization. Every day a property remains vacant represents lost cash flow. We coordinate renovation completion, listing, applicant screening, inspections, PHA approvals, and move-in requirements with the goal of minimizing downtime.",
        "The result is a leasing platform designed around the realities of affordable housing: strict tenant selection, precise government-process execution, and rapid conversion of renovated homes into occupied, income-producing assets. We don't just lease the house. We stabilize the asset.",
      ],
      image: "/images/process-leasing.png",
    },
    {
      id: "4",
      name: "Stabilization",
      title: "Step 4. Stabilize: From Occupancy to Durable Cash Flow",
      paragraphs: [
        "Leasing a home is only the beginning of the operating cycle. Obelisk treats the post-leasing period as a critical stabilization phase—where we address the realities of living in the home, establish a productive relationship with the tenant, and bring the property to a predictable and sustainable NOI level. Our approach is proactive rather than reactive.",
        "Respond to the Home. Tenant feedback and move-in requests often reveal items that cannot be fully identified during the initial renovation. We address reasonable post-leasing repairs and improvements promptly, prioritizing health, safety, habitability, and issues that can materially affect long-term property performance.",
        "Respond to Maintenance Quickly. Timely maintenance is essential to protecting both the tenant relationship and the asset. We focus on resolving issues before they become larger and more expensive problems, while maintaining disciplined control over repair costs.",
        "Manage Tenant Expectations. Affordable housing requires a practical balance between resident satisfaction and responsible asset management. We establish clear expectations around maintenance, property care, rent obligations, lease compliance, and communication. The goal is a stable landlord–tenant relationship rather than simply minimizing short-term costs.",
        "Stabilize Property Economics. Once the home is occupied and operating history begins to accumulate, we closely monitor rent collection, maintenance, utilities, insurance, property taxes, vacancy, and other operating expenses. We use this information to identify deviations from underwriting assumptions and take corrective action where necessary.",
        "The objective is not to maximize NOI through aggressive cost-cutting. It is to establish a reasonable, repeatable, and durable NOI that reflects the actual economics of the property. For Obelisk, stabilization means the home has moved beyond the acquisition and renovation thesis and proven itself in operation: Occupied. Maintained. Predictable. Cash-flowing. That is when an individual property becomes a reliable institutional asset.",
      ],
      image: "/images/process-stabilization.png",
    },
    {
      id: "5",
      name: "Refinance",
      title: "Step 5. Refinance: Recycle Capital, Compound Scale",
      paragraphs: [
        "Once a property has been renovated, leased, and stabilized, Obelisk evaluates refinancing opportunities based on the property's stabilized cash flow, market value, and prudent leverage capacity. Refinancing serves an important purpose in our investment model: capital recycling.",
        "Rather than allowing the initial equity invested in a stabilized property to remain permanently locked in the asset, we seek to refinance when market conditions and property-level economics support attractive terms. A portion of the original equity can thereby be returned to investors while the property remains in the portfolio and continues to generate rental income.",
        "This creates a powerful compounding mechanism. Acquire → Improve → Lease → Stabilize → Refinance → Reinvest.",
        "The capital returned through refinancing is not automatically required to be withdrawn from the platform. At each investor's discretion, recycled capital may be redeployed into subsequent Obelisk funds and used to acquire additional properties. This allows investors to potentially increase their exposure to the portfolio without requiring the same amount of new capital for every stage of portfolio growth.",
        "Importantly, Obelisk approaches refinancing conservatively. The objective is not to maximize leverage, but to find the appropriate balance between capital recovery, ongoing cash flow, debt service coverage, and long-term asset resilience. As the portfolio scales, this capital recycling mechanism can shorten the distance between one investment cycle and the next—allowing proven assets to help fund the acquisition of future assets.",
        "We don't just create value. We recycle it into the next opportunity.",
      ],
      image: "/images/process-refinancing.png",
    },
    {
      id: "6",
      name: "Scaling",
      title: "Step 6. Scale: Build Density, Replicate the Model",
      paragraphs: [
        "Once Obelisk has established a proven operating model in Birmingham, we seek to scale the platform through greater portfolio density and selective expansion into additional markets.",
        "Scaling within Birmingham is the first priority. By concentrating properties within selected neighborhoods and submarkets, Obelisk can deepen its local market knowledge, sourcing relationships, contractor network, and operating infrastructure. Greater density allows us to standardize acquisition, renovation, leasing, and property management while improving operating efficiency and generating increasingly valuable property-level data. ",
        "This creates a powerful local scaling mechanism. Acquire → Improve → Lease → Stabilize → Refinance → Reinvest → Build Density.",
        "As the Birmingham portfolio reaches sufficient scale and the operating model becomes increasingly standardized, Obelisk can selectively replicate the platform in other affordable housing markets with similar underlying characteristics. ",
        "We evaluate new markets based on factors including housing affordability, rental demand, acquisition opportunities, Section 8 economics, operating costs, regulatory environment, and the availability of local operating partners. The objective is not to expand geographically for its own sake, but to identify markets where the Obelisk model can be reproduced with comparable risk-adjusted economics.",
        "Importantly, Obelisk approaches geographic expansion deliberately. We do not intend to sacrifice underwriting discipline, renovation standards, tenant quality, or operating control simply to increase the number of homes in the portfolio. Each new market must demonstrate that the operating model can be established, managed, and scaled effectively before significant capital is deployed.",
        "Over time, this approach allows Obelisk to evolve from a Birmingham-focused portfolio into a multi-market affordable housing platform, while preserving the local expertise and operational discipline that created the initial competitive advantage. ",
        "Build density. Prove the model. Replicate what works. Compound scale.",
      ],
      image: "/images/process-scaling.png",
    },
  ],
  disclosure:
    "Disclosure: The information contained on this website is provided for informational purposes only and does not constitute an offer to sell, or a solicitation of an offer to purchase, any security, investment product, or investment advisory service. Any such offer or solicitation will be made only through applicable offering documents and only to qualified investors in jurisdictions where permitted by law. Investments involve risk, including the possible loss of principal. Past performance is not indicative of future results.",
} as const;
