window.OBK = {
  nav: [{key:"/",label:"Home"},{key:"/portfolio",label:"Portfolio"},{key:"/investor-login",label:"Investor Login"},{key:"/investor-home",label:"Investor Home"},{key:"/fund-iii-portfolio",label:"Fund III Portfolio"},{key:"/property-performance",label:"Property Performance"}],
  photos: [
    {id:"9645-9th-ave-n",pid:1,address:"9645 9th Ave N",location:"Birmingham, AL 35217",status:"Rented",rent:"$1,150",acq:"2022-03-14",cost:"$61,400",reno:"$18,200",total:"$79,600"},
    {id:"213-22nd-st-sw",pid:2,address:"213 22nd St SW",location:"Birmingham, AL 35211",status:"Rented",rent:"$1,095",acq:"2022-05-02",cost:"$54,900",reno:"$21,750",total:"$76,650"},
    {id:"4129-avenue-q",pid:3,address:"4129 Avenue Q",location:"Birmingham, AL 35208",status:"Rented",rent:"$1,200",acq:"2022-06-21",cost:"$58,300",reno:"$16,900",total:"$75,200"},
    {id:"4011-43rd-ave-n",pid:4,address:"4011 43rd Ave N",location:"Birmingham, AL 35217",status:"Leasing",rent:null,acq:"2022-09-08",cost:"$49,800",reno:"$24,100",total:"$73,900"},
    {id:"7809-vienna-avenue",pid:5,address:"7809 Vienna Avenue",location:"Birmingham, AL 35206",status:"Rented",rent:"$1,250",acq:"2023-01-17",cost:"$66,000",reno:"$14,300",total:"$80,300"},
    {id:"4617-n-richard-arrington-jr-blvd-n",pid:6,address:"4617 N Richard Arrington Jr Blvd N.",location:"Birmingham, AL 35212",status:"Rented",rent:"$1,100",acq:"2023-02-28",cost:"$52,500",reno:"$19,600",total:"$72,100"},
    {id:"1444-30th-street-ensley",pid:7,address:"1444 30th Street Ensley",location:"Birmingham, AL 35218",status:"Pending Sec 8",rent:null,acq:"2023-04-11",cost:"$47,200",reno:"$22,800",total:"$70,000"},
    {id:"4401-avenue-i",pid:38,address:"4401 Avenue I",location:"Birmingham, AL 35218",status:"Rented",rent:"$1,175",acq:"2026-06-22",cost:"$71,000",reno:null,total:null,pending:true}
  ].map(p=>({...p,image:"../../assets/photos/"+p.id+".jpg"})),
  steps: [
    {id:"1",name:"Acquisition",overview:"Identify and acquire undervalued, affordable single-family homes in strong rental markets.",tagline:"Buy Right.",title:"Acquisition of Undervalued Affordable Single Family Homes",lead:"Obelisk specializes in acquiring undervalued affordable single-family homes in select U.S. markets where replacement costs significantly exceed acquisition costs and long-term rental demand remains durable. Our acquisition strategy is designed to create value at the point of purchase rather than relying on market appreciation alone.",image:"../../assets/illustrations/process-acquisition.png"},
    {id:"2",name:"Renovation",overview:"Execute cost-effective renovations to meet Section 8 standards with durability and tenant appeal.",tagline:"Improve Smart.",title:"Renovation: Compliance-Led, Value-Engineered",lead:"Our objective is not to maximize renovation spend or create luxury homes. It is to deliver safe, durable, attractive housing that performs above Section 8 requirements—without over-improving the asset.",image:"../../assets/illustrations/process-renovation.png"},
    {id:"3",name:"Leasing",overview:"Rigorous tenant screening and expert handling of government procedures to secure qualified tenants quickly.",tagline:"Lease Well.",title:"Leasing: Disciplined Screening, Expert Execution",lead:"Leasing affordable housing requires more than filling vacancies. Obelisk combines rigorous tenant screening with deep proficiency in government housing programs to convert renovated properties into stable, cash-flowing assets.",image:"../../assets/illustrations/process-leasing.png"},
    {id:"4",name:"Stabilization",overview:"Deliver responsive maintenance, manage expectations, and drive properties to stable, predictable NOI.",tagline:"Stabilize Value.",title:"Stabilize: From Occupancy to Durable Cash Flow",lead:"Leasing a home is only the beginning of the operating cycle. Obelisk treats the post-leasing period as a critical stabilization phase—where we address the realities of living in the home, establish a productive relationship with the tenant, and bring the property to a predictable and sustainable NOI level.",image:"../../assets/illustrations/process-stabilization.png"},
    {id:"5",name:"Refinance",overview:"Refinance stabilized assets to recycle capital and compound portfolio growth at investors’ discretion.",tagline:"Recycle Capital.",title:"Refinance: Recycle Capital, Compound Scale",lead:"Once a property has been renovated, leased, and stabilized, Obelisk evaluates refinancing opportunities based on the property's stabilized cash flow, market value, and prudent leverage capacity. Refinancing serves an important purpose in our investment model: capital recycling.",image:"../../assets/illustrations/process-refinancing.png"},
    {id:"6",name:"Scaling",overview:"Reinvest capital and repeat the cycle to build a concentrated, high-quality portfolio.",tagline:"Scale Impact.",title:"Scale: Build Density, Replicate the Model",lead:"Once Obelisk has established a proven operating model in Birmingham, we seek to scale the platform through greater portfolio density and selective expansion into additional markets.",image:"../../assets/illustrations/process-scaling.png"}
  ]
};
